### ISSUE TITLE
Incorrect handle for the replacement script

### ISSUE THREAD

**Issue by nyordanov** [Remzi1993/wp-jquery-manager#2] opened 2018-11-23 13:53 UTC
https://github.com/Remzi1993/wp-jquery-manager/blob/4ca4ec9c841d8b88f835e0cc848c1e0043dfbdbe/wp-jquery-manager.php#L312

WP actually uses the `jquery-core` handle, not `jquery`:

https://github.com/WordPress/WordPress/blob/91da29d9afaa664eb84e1261ebb916b18a362aa9/wp-includes/script-loader.php#L226

**Comment by Remzi1993** [comment] 2018-11-25 09:26
@nyordanov  Thank you very much!

Is this the same in the front-end and back-end? 

I see the following code:
```
// jQuery
$scripts->add( 'jquery', false, array( 'jquery-core', 'jquery-migrate' ), '1.12.4' );
$scripts->add( 'jquery-core', '/wp-includes/js/jquery/jquery.js', array(), '1.12.4' );
$scripts->add( 'jquery-migrate', "/wp-includes/js/jquery/jquery-migrate$suffix.js", array(), '1.4.1' );
```

Does this mean that the handle `jquery` depends on the handle `jquery-core`?

**EDIT**
If I change the script handle to `jquery-core` I seem to get a blank page on the front-end without any error messages: `wp_deregister_script('jquery-core');` and then I enqueue: `wp_enqueue_script( 'jquery-core', WP_JQUERY_MANAGER_PLUGIN_DIR_URL . $jquery_version, array(), null, false );`

I will look further into this, it looks like I'm missing something

**Comment by Remzi1993** [comment] 2018-11-25 21:58
Hi @nyordanov you were right! I'm so thankful that you pointed that out. (otherwise I wouldn't know)
I have updated my code, version 1.5.0 includes the following fix:

```
// Deregister WP core jQuery
wp_deregister_script( 'jquery' );
wp_deregister_script( 'jquery-core' );

// Default jQuery version
$jquery_version = 'assets/js/' . WP_JQUERY_MANAGER_PLUGIN_JQUERY_3X . '.min.js';

// Register jQuery in the head
wp_register_script( 'jquery-core', WP_JQUERY_MANAGER_PLUGIN_DIR_URL . $jquery_version, array(), null, false );

/**
 * Register jquery using jquery-core as a dependency, so other scripts could use the jquery handle
 * see https://wordpress.stackexchange.com/questions/283828/wp-register-script-multiple-identifiers
 * We first register the script and afther that we enqueue it, see why:
 * https://wordpress.stackexchange.com/questions/82490/when-should-i-use-wp-register-script-with-wp-enqueue-script-vs-just-wp-enque
 * https://stackoverflow.com/questions/39653993/what-is-diffrence-between-wp-enqueue-script-and-wp-register-script
 */
wp_register_script( 'jquery', false, array( 'jquery-core' ), null, false );
wp_enqueue_script( 'jquery' );
```

I also have updated the repository could you check and test if everything works as intended?

**Comment by Remzi1993** [comment] 2018-11-26 16:43
Hi @nyordanov 
I have made changes accordingly to the code to address this and therefore I'm closing this ticket.
If you think otherwise please let me know and reply to this ticket, so I could take a look.

After some testing I have release version 1.6.0 with a mention to you. (again thank you)

Kind Regards,

Remzi

**Closed as completed by Remzi1993** 2018-11-26 16:43 UTC
